"""buy sell models.py 10 april 25

Revision ID: 62d331f5cdd7
Revises: 
Create Date: 2025-04-10 21:13:57.398842
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '62d331f5cdd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_table('stock_index_data_cache')

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.create_index(batch_op.f('ix_holdings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('transaction_date',
                              existing_type=sa.DATETIME(),
                              nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
                              existing_type=sa.NUMERIC(precision=10, scale=2),
                              nullable=False)
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              nullable=False)
        batch_op.alter_column('is_active',
                              existing_type=mssql.BIT(),
                              nullable=False)

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index('ix_watchlist_user_id')
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('added_at',
                              existing_type=sa.DATETIME(),
                              nullable=False)
        batch_op.create_index('ix_watchlist_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index('ix_watchlist_user_id')
        batch_op.alter_column('added_at',
                              existing_type=sa.DATETIME(),
                              nullable=True)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.create_index('ix_watchlist_user_id', ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
                              existing_type=mssql.BIT(),
                              nullable=True)
        batch_op.alter_column('created_at',
                              existing_type=sa.DATETIME(),
                              nullable=True)
        batch_op.alter_column('balance',
                              existing_type=sa.NUMERIC(precision=10, scale=2),
                              nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.alter_column('transaction_date',
                              existing_type=sa.DATETIME(),
                              nullable=True)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_user_id'))
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    op.create_table('stock_index_data_cache',
        sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
        sa.Column('symbol', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), nullable=False),
        sa.Column('name', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), nullable=False),
        sa.Column('type', sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), nullable=False),
        sa.Column('open_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('high_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('low_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('close_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('volume', sa.INTEGER(), nullable=True),
        sa.Column('market_cap', sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column('pe_ratio', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('change', sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column('percent_change', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('last_updated', sa.DATETIME(), server_default=sa.text('(getdate())'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='PK__stock_in__3213E83F012E7E61')
    )
    # ### end Alembic commands ###
