"""Add executed_at to Transaction

Revision ID: b9f19c2fd28e
Revises: 3418c42152dd
Create Date: 2025-06-13 14:33:44.891644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f19c2fd28e'
down_revision = '3418c42152dd'
branch_labels = None
depends_on = None


def upgrade():
    # Add executed_at with a default value to avoid SQL Server error
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'executed_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.text("(GETUTCDATE())")  # Use SQL Server UTC time
            )
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('executed_at')

    # ### end Alembic commands ###
